# Generated by Django 4.1.3 on 2023-01-09 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Customer',
        ),
    ]
