# Generated by Django 4.1.5 on 2023-01-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="customer_id",
            new_name="customer",
        ),
        migrations.AlterField(
            model_name="payment",
            name="product_name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
