# Generated by Django 4.1.7 on 2023-03-14 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('paternal_surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payments_cunstomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('cunstomer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webApp.customers')),
            ],
        ),
    ]
