# Generated by Django 4.1.3 on 2023-02-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrators',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentscustomers',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
