# Generated by Django 4.1.7 on 2023-03-14 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments_cunstomers',
            new_name='PaymentsCustomers',
        ),
    ]
