# Generated by Django 4.1.7 on 2023-03-14 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_rename_payments_cunstomers_paymentscustomers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentscustomers',
            old_name='cunstomer',
            new_name='customer',
        ),
    ]
