# Generated by Django 4.1.3 on 2023-03-09 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_rename_administrators_administrator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
