# Generated by Django 4.1.3 on 2023-02-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_alter_administrators_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
