# Generated by Django 4.1.7 on 2023-03-14 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0003_rename_cunstomer_paymentscustomers_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='PaymentsCustomers',
            new_name='PaymentCustomer',
        ),
    ]
